name: Docker Image CI

on:
  push:
    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
  workflow_dispatch:

env:
  GUACD_Version: 1.5.3

jobs:
        
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Check envs
      run: |
        echo ${{ env }}
    
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Download guacamole-server
      run: |
        wget -O guacamole-server-"${{ env.GUACD_Version }}".tar.gz https://apache.org/dyn/closer.lua/guacamole/"${{ env.GUACD_Version }}"/source/guacamole-server-"${{ env.GUACD_Version }}".tar.gz?action=download
        mkdir -p ./guacamole-server
        tar -xzf guacamole-server-"${{ env.GUACD_Version }}".tar.gz -C ./guacamole-server --strip-components=1
    
    - name: ls
      run: ls ./guacamole-server
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    #- name: Build and push
    #  uses: docker/build-push-action@v5
     # with:
      #  context: .
       # platforms: linux/amd64,linux/arm/v7,linux/arm64
       # push: true
        #tags: |
         #  ${{ github.repository }}:${{ env.GUACD_Version }}
          # ${{ github.repository }}:latest
