name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  GUACD_Version: 1.5.3
  DOCKER_IMAGE: redgate/flyway
  SCHEMAS: etslips

jobs:
        
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Create folder
      run: mkdir -p ./guacamole-server
    
    - name: wget
      uses: wei/wget@v1
      with:
        args: -O ./guacamole-server/guacamole-server-"${{ env.GUACD_Version }}".tar.gz https://apache.org/dyn/closer.lua/guacamole/"${{ env.GUACD_Version }}"/source/guacamole-server-"${{ env.GUACD_Version }}".tar.gz?action=download
    
    - name: ls
      run: ls ./guacamole-server
    
    
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
